README.md:
	echo " # This is second level of Arcade in codefights.">README.md
	echo "---">>README.md
	echo "|Level| site|">>README.md
	echo "|-----|-----|">>README.md
	echo "| two |codefights|">>README.md
	echo "---">>README.md
	echo "> ### It includes the following program">>README.md
	echo "* finding the area">> README.md
	echo "```function shapeArea(n) {return n==1?1:((n-1)*4+shapeArea(n-1)); }```">>README.md
	echo "* finding the max adjacent Element Product">> README.md
	echo "``` function adjacentElementsProduct(arr) { return Math.max(...arr.slice(1).map((x,i)=>[x*arr[i]]))}```">>README.md
	echo "* checking whether the sequence is strictly increasing when removing no">>README.md
	echo "* getting the sum after applying some conditions">>README.md
	echo "* getting the no of elements needed to make an array consecutive.">>README.md
	echo "### Time at which I Pushed it to Github">>README.md
	date>>README.md
	echo "### Number of files in the directory">>README.md
	echo "---">>README.md
	echo "**created by** *AMAN BASSI*">>README.md
	echo "### Number of files in the directory:">>README.md
	ls|wc -l>>README.md
	echo "### Link to my Github Page for the description">> README.md
	echo "[Github_Page](https://rapt007.github.io/codefights/codefights/EdgeOfTheOcean/)">>README.md
